name: Terraform Buckets

on:
  push:
    paths:
      - 'buckets/**'
  pull_request:
    paths:
      - 'buckets/**'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      aws_access_key_id: ${{ steps.assume_role.outputs.aws_access_key_id }}
      aws_secret_access_key: ${{ steps.assume_role.outputs.aws_secret_access_key }}
      aws_session_token: ${{ steps.assume_role.outputs.aws_session_token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Assume My_Infra_Role and export credentials
        id: assume_role
        run: |
          CREDS_JSON=$(aws sts assume-role \
            --role-arn arn:aws:iam::103056765659:role/My_Infra_Role \
            --role-session-name github-actions-session)
          echo "aws_access_key_id=$(echo $CREDS_JSON | jq -r .Credentials.AccessKeyId)" >> $GITHUB_OUTPUT
          echo "aws_secret_access_key=$(echo $CREDS_JSON | jq -r .Credentials.SecretAccessKey)" >> $GITHUB_OUTPUT
          echo "aws_session_token=$(echo $CREDS_JSON | jq -r .Credentials.SessionToken)" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2

  website-1-stage:
    needs: setup
    runs-on: ubuntu-latest
    environment: prod
<<<<<<< HEAD
    # Only run this job if buckets/website-1/terraform.tfvars changes
    paths:
      - 'buckets/website-1/terraform.tfvars'
=======
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(join(github.event.commits.*.modified, ' '), 'buckets/website-1/terraform.tfvars') ||
      contains(join(github.event.commits.*.added, ' '), 'buckets/website-1/terraform.tfvars') ||
      contains(join(github.event.commits.*.removed, ' '), 'buckets/website-1/terraform.tfvars')
>>>>>>> 8c0c66320d8639c64072ebe1ec97b1898514ead0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
      - name: Terraform Init, Plan, Apply/Destroy
        working-directory: buckets/website-1
        env:
          AWS_ACCESS_KEY_ID: ${{ needs.setup.outputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ needs.setup.outputs.aws_secret_access_key }}
          AWS_SESSION_TOKEN: ${{ needs.setup.outputs.aws_session_token }}
        run: |
          set -e
          terraform init
          terraform plan -out=tfplan

          CREATE=$(grep '^create' terraform.tfvars | awk -F'=' '{print tolower($2)}' | tr -d ' "')
          DELETE=$(grep '^delete' terraform.tfvars | awk -F'=' '{print tolower($2)}' | tr -d ' "')

          if [ "$CREATE" = "true" ]; then
            echo "Running terraform apply..."
            terraform apply -auto-approve tfplan
          fi

          if [ "$DELETE" = "true" ]; then
            echo "Running terraform destroy..."
            terraform destroy -auto-approve
          fi
      - name: Cleanup AWS credentials
        if: always()
        run: |
          echo "AWS_ACCESS_KEY_ID=dummy" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=dummy" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=dummy" >> $GITHUB_ENV
