name: Terraform Parent Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'buckets/**'
      - 'modules/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'buckets/**'
      - 'modules/**'
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Specific bucket to deploy (optional)'
        required: false
        type: string

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-buckets: ${{ steps.detect-changes.outputs.changed-buckets }}
      all-buckets: ${{ steps.get-buckets.outputs.all-buckets }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all bucket directories
        id: get-buckets
        run: |
          BUCKETS=$(find buckets/ -maxdepth 1 -type d -name "website-*" | sed 's|buckets/||' | tr '\n' ',' | sed 's/,$//')
          echo "all-buckets=$BUCKETS" >> $GITHUB_OUTPUT
          echo "Found buckets: $BUCKETS"

      - name: Detect changed buckets
        id: detect-changes
        run: |
          # If workflow_dispatch with specific bucket, use that
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ github.event.inputs.bucket_name }}" ]; then
            echo "Manual trigger for bucket: ${{ github.event.inputs.bucket_name }}"
            echo "changed-buckets=${{ github.event.inputs.bucket_name }}" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Get changed files
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          else
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          fi
          
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Detect which buckets have changes
          CHANGED_BUCKETS=""
          ALL_BUCKETS="${{ steps.get-buckets.outputs.all-buckets }}"
          
          for bucket in ${ALL_BUCKETS//,/ }; do
            if echo "$CHANGED_FILES" | grep -q "buckets/$bucket/"; then
              if [ -z "$CHANGED_BUCKETS" ]; then
                CHANGED_BUCKETS="$bucket"
              else
                CHANGED_BUCKETS="$CHANGED_BUCKETS,$bucket"
              fi
            fi
          done
          
          # Also check if modules changed (affects all buckets)
          if echo "$CHANGED_FILES" | grep -q "modules/"; then
            echo "Modules changed, will trigger all buckets"
            CHANGED_BUCKETS="$ALL_BUCKETS"
          fi
          
          echo "Changed buckets: $CHANGED_BUCKETS"
          echo "changed-buckets=$CHANGED_BUCKETS" >> $GITHUB_OUTPUT

  trigger-child-pipelines:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.changed-buckets != ''
    strategy:
      matrix:
        bucket: ${{ fromJson(format('[{0}]', needs.detect-changes.outputs.changed-buckets)) }}
    steps:
      - name: Trigger pipeline for ${{ matrix.bucket }}
        run: |
          echo "Triggering pipeline for bucket: ${{ matrix.bucket }}"
          
          # Create workflow dispatch event
          gh workflow run terraform-${{ matrix.bucket }}.yml \
            --ref ${{ github.ref }} \
            --field bucket_name=${{ matrix.bucket }} \
            --field trigger_source=parent_pipeline
          
          echo "Pipeline triggered for ${{ matrix.bucket }}"

  summary:
    needs: [detect-changes, trigger-child-pipelines]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Summary
        run: |
          echo "## Terraform Parent Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Changed Buckets:** ${{ needs.detect-changes.outputs.changed-buckets }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**All Buckets:** ${{ needs.detect-changes.outputs.all-buckets }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Trigger Source:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Manual Trigger Bucket:** ${{ github.event.inputs.bucket_name }}" >> $GITHUB_STEP_SUMMARY
          fi 